### ISSUE TITLE
Failed to activate the tokamak package

### ISSUE THREAD

**Issue by vertexclique** [vertexclique/tokamak#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.3
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package, v0.2.2

### Stack Trace

Failed to activate the tokamak package

```
At fs is not defined

ReferenceError: fs is not defined
    at new AboutView (/Users/vertexclique/projects/tokamak/lib/about-view.coffee:13:20)
    at Object.module.exports.Tokamak.activate (/Users/vertexclique/projects/tokamak/lib/tokamak.coffee:75:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -5:36.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:34.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -5:34.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:30.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:30.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:21.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:19.4.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -5:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:01.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:00.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -4:54.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
tokamak, v0.2.2

# Dev
No dev packages
```

**Comment by vertexclique** [comment]
4a9ba68 closes

**Comment by AllesCoolAllesBestens** [comment]
I just tried to install tokamak and I still get this error, Atom sends me to this issue.

[Enter steps to reproduce below:]

1. Install with "apm install tokamak"
2. Start atom

**Atom Version**: 1.9.6
**System**: linux 4.6.4-1-ARCH
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package, v0.2.8


### Stack Trace

Failed to activate the tokamak package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1253:7)
    at Function.module.exports.Utils.isTokamakProject (/home/florian/.atom/packages/tokamak/lib/utils.coffee:115:24)
    at Object.module.exports.Tokamak.activate (/home/florian/.atom/packages/tokamak/lib/tokamak.coffee:87:14)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:760:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.8.0 (inactive)
git-plus, v5.2.2 (inactive)
language-x86asm, v0.5.1 (inactive)
tokamak, v0.2.8 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by MSleepyPanda** [comment]
Same issue on windows, tokamak doesn't start

**Comment by justinbrewer** [comment]
Same issue. Fresh install of Atom, installed Tokamak, got the error.

**Comment by vertexclique** [comment]
@justinbrewer what is your version?

**Comment by justinbrewer** [comment]
@vertexclique Atom 1.9.8, Tokamak 0.3.0. Running on Archlinux.

**Comment by vertexclique** [comment]
@justinbrewer can you please paste the trace too?

**Comment by justinbrewer** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.8
**System**: linux 4.6.3-1
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package, v0.3.0


### Stack Trace

Failed to activate the tokamak package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Function.module.exports.Utils.isTokamakProject (/home/jbrewer/.atom/packages/tokamak/lib/utils.coffee:117:24)
    at Object.activate (/home/jbrewer/.atom/packages/tokamak/lib/tokamak.coffee:87:14)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:183:20)
    at /usr/lib/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
    at /usr/lib/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:530:21)
    at /usr/lib/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib/atom/src/package-manager.js:489:46)
    at /usr/lib/atom/src/atom-environment.js:760:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
tokamak, v0.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by PAStheLoD** [comment]
Latest iteration of this issue :(

Tokamak 0.3.2
atom 1.14.4

The problem is that I had an invalid value for "Path to MultiRust or RustUp installation manager", so that should be validated too.

```
TypeError: Cannot read property 'path' of undefined
  at Function.module.exports.Utils.parseTokamakConfig (/home/pas/.atom/packages/tokamak/lib/utils.coffee:125:62)
  at Object.tokamakProjectConfigLaunch (/home/pas/.atom/packages/tokamak/lib/tokamak.coffee:112:28)
  at Object.activate (/home/pas/.atom/packages/tokamak/lib/tokamak.coffee:96:10)
  at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:218:19)
  at /opt/atom/resources/app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:96:15)
  at /opt/atom/resources/app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:550:34)
  at /opt/atom/resources/app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/opt/atom/resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:508:46)
  at /opt/atom/resources/app.asar/src/atom-environment.js:814:28
```
