### ISSUE TITLE
Uncaught TypeError: Bad argument.

### ISSUE THREAD

**Issue by emreyaren** [vertexclique/tokamak#11]
[Enter steps to reproduce below:]

1. ...Click Terminal button
2. ...

**Atom Version**: 1.6.2
**System**: "Fedora release
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package, v0.2.5

### Stack Trace

Uncaught TypeError: Bad argument.

```
At /usr/share/atom/resources/app.asar/node_modules/nodegit/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:18

TypeError: Bad argument.
    at TypeError (native)
    at process.chdir (/usr/share/atom/resources/app.asar/node_modules/nodegit/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:18:9)
    at CargoView.module.exports.CargoView.cargoCmdRunner (/home/hemre/.atom/packages/tokamak/lib/cargo-view.coffee:73:13)
    at CargoView.module.exports.CargoView.attachCargo (/home/hemre/.atom/packages/tokamak/lib/cargo-view.coffee:49:6)
    at atom-workspace.commandSubscription.atom.commands.add.tokamak:clean (/home/hemre/.atom/packages/tokamak/lib/cargo-view.coffee:27:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at module.exports._executeCallback (/home/hemre/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:71:23)
    at space-pen-button.<anonymous> (/home/hemre/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:30:7)
    at space-pen-button.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-button.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:00.6.0 tokamak:clean (atom-text-editor.editor)
```

### Config

```json
{
  "tokamak": {
    "racerBinPath": "/home/hemre/.multirust/toolchains/stable/cargo/bin/racer"
  }
}
```

### Installed Packages

```coffee
# User
cursor-blink-interval, v0.3.1
language-rust, v0.4.6
linter, v1.11.4
linter-rust, v0.4.5
racer, v0.18.0
tokamak, v0.2.5
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by SkeLLLa** [comment]
Any fixes planned for this? The plugin is unusable.
