### ISSUE TITLE
Uncaught ReferenceError: mode is not defined

### ISSUE THREAD

**Issue by nohupped** [vertexclique/tokamak#72]
[Enter steps to reproduce:]

1. Open atom
2. Click on Create project
3. Select any of the "Create Cargo Library" or "Create Cargo Binary"
That's it. It will throw error.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.1
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package 0.3.2

### Stack Trace

Uncaught ReferenceError: mode is not defined

```
At /home/girishg/.atom/packages/tokamak/lib/cargo-view.coffee:57

ReferenceError: mode is not defined
    at CargoView.module.exports.CargoView.attach (/packages/tokamak/lib/cargo-view.coffee:57:34)
    at /packages/tokamak/lib/cargo-view.coffee:31:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at CreateProjectView.module.exports.CreateProjectView.confirmed (/packages/tokamak/lib/create-project-view.coffee:38:28)
    at CreateProjectView.module.exports.SelectListView.confirmSelection (/packages/tokamak/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at /packages/tokamak/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.dispatch (/packages/tokamak/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/packages/tokamak/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:08.4.0 editor:newline (input.hidden-input)
  2x -0:07.3.0 core:backspace (input.hidden-input)
     -0:05.0 tokamak:create-project (input.hidden-input)
     -0:03.0 tokamak:create-cargo-binary (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax)
```

### Non-Core Packages

```
auto-detect-indentation 1.3.0 
autocomplete-clang 0.10.0 
build-tools 4.5.7 
busy-signal 1.3.0 
darcula-syntax 0.2.0 
gcc-make-run 0.2.9 
gpp-compiler 3.0.7 
highlight-selected 0.12.0 
intentions 1.1.2 
language-rust 0.4.10 
linter 2.1.0 
linter-rust 0.7.3 
linter-ui-default 1.2.1 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
nucleus-dark-ui 0.11.0 
racer 0.20.0 
rusty-dark-syntax 0.6.3 
script 3.14.1 
script-runner 2.1.1 
todo-show 1.11.0 
tokamak 0.3.2 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
```

**Comment by nbro** [comment]
Same problem, but with different settings.

Atom: 1.16.0 x64
OS: macOS 10.12.4 (Sierra)

Here's the error dialog:

<img width="460" alt="screen shot 2017-04-14 at 21 57 44" src="https://cloud.githubusercontent.com/assets/9349000/25054459/88071620-215d-11e7-87fa-bf191d316151.png">

and if I click on _Show Stack Trace_:

> ReferenceError: mode is not defined
    at CargoView.module.exports.CargoView.attach (/Users/cell/.atom/packages/tokamak/lib/cargo-view.coffee:57:34)
    at atom-workspace.commandSubscription.atom.commands.add.tokamak:create-cargo-library (/Users/cell/.atom/packages/tokamak/lib/cargo-view.coffee:30:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
