### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by charlenopires** [vertexclique/tokamak#78]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'options' of undefined

```
At /Users/charlenopires/.atom/packages/tokamak/lib/tokamak.js:206

TypeError: Cannot read property 'options' of undefined
    at /packages/tokamak/lib/tokamak.js:206:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:106:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:70:7)
```

### Commands

```
     -9:44.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -9:42.7.0 editor:consolidate-selections (input.hidden-input)
     -9:42.7.0 core:cancel (input.hidden-input)
     -9:42.3.0 application:open (input.hidden-input)
     -9:38.4.0 editor:consolidate-selections (input.hidden-input)
     -9:38.4.0 core:cancel (input.hidden-input)
     -9:34.5.0 tokamak:create-project (input.hidden-input)
     -9:31.7.0 tokamak:create-cargo-binary (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -9:28.3.0 editor:consolidate-selections (input.hidden-input)
     -9:28.3.0 core:cancel (input.hidden-input)
     -9:21.6.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -7:55.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:29.4.0 tabs:split-left (div.title)
     -0:09.8.0 tokamak:run (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.3.3 
busy-signal 1.4.3 
ide-reason 0.1.3 
intentions 1.1.5 
language-rust 0.4.12 
languageserver-rust 0.3.0 
linter 2.2.0 
linter-rust 0.8.0 
linter-ui-default 1.6.10 
rust-api-docs-helper 0.5.1 
rust-doc-viewer 2.6.3 
rustfmt 0.1.3 
tokamak 0.4.0 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
```

**Comment by gugahoa** [comment]
This can be solved restarting Atom

**Comment by devilbuddy** [comment]
[Enter steps to reproduce:]

1. create new project
2. hit "play" button (cargo run)

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package 0.4.0


### Stack Trace

Uncaught TypeError: Cannot read property 'options' of undefined

```
At /home/magnus/.atom/packages/tokamak/lib/tokamak.js:206

TypeError: Cannot read property 'options' of undefined
    at /packages/tokamak/lib/tokamak.js:206:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:106:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:70:7)
```

### Commands

```
     -0:21.2.0 tokamak:run (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-ide-ui 0.3.3 
busy-signal 1.4.3 
intentions 1.1.5 
language-rust 0.4.12 
tokamak 0.4.0 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
```

**Comment by gugahoa** [comment]
@devilbuddy try adding the project folder to atom, using Ctrl+Shift+A, and the restarting

**Comment by devilbuddy** [comment]
@gugahoa - unfortunately same problem
