### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by gugahoa** [vertexclique/tokamak#79]
[Steps to reproduce:]

1. Install Tokamak
2. Open Atom without a project folder
3. Click in Create Tokamak Configuration

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: "Fedora release
**Thrown From**: [tokamak](https://github.com/vertexclique/tokamak) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /home/gugah/.atom/packages/tokamak/lib/utils.coffee:146

TypeError: Cannot read property 'path' of undefined
    at Function.module.exports.Utils.createDefaultTokamakConfig (/packages/tokamak/lib/utils.coffee:146:48)
    at /packages/tokamak/lib/tokamak.js:222:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:106:19)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:70:7)
```

### Commands

```
     -0:01.4.0 tokamak:create-tokamak-configuration (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.3.3 
atom-typescript 11.0.9 
autocomplete-python 1.10.2 
busy-signal 1.4.3 
ide-typescript 0.1.6 
intentions 1.1.5 
language-docker 1.1.8 
language-elixir 0.20.2 
language-rust 0.4.12 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-ui-default 1.6.10 
pretty-json 1.6.4 
relative-numbers 0.8.0 
tokamak 0.4.0 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
vim-mode-plus 1.5.0 
```

**Comment by gugahoa** [comment]
The same will happen if you try to create a Cargo Library/Binary, as it will not open the (successfully) created project as the root directory
